spring:
  application:
    name: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/redis_sample
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
